In [1]:
import numpy as np

# Завдання
## 1. Створити двомірний нульовий масив розміром 11х11 та заповнити його діагоналі одиницями.

1.1. Задати розмір масиву

In [2]:
size = 11

1.2. Створити нульовий масив заданого розміру

In [3]:
arr = np.zeros([size, size])

1.3 Надрукувати створений масив

In [4]:
print(arr)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


1.4 Змінити діагоналі за допомогою двох циклів

In [5]:
for i in range(size):
	for j in range(size):
		if (i==j):
			arr[i][j] = 1
		elif (j==size-i-1):
			arr[j][i] = 1

1.5 Вивести створений масив

In [6]:
print(arr)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


## 2. Засобами NumPy створити вертикальні та горизонтальні зображення градієнту в обидва боки (поступове збільшення яскравості на зображенні).

Приклад зображення градієнту
<img src="./horizontal_grad.jpg" height="200" width="200">

### Горизонтальний градієнт

2.1 Створити нульовий масив розміром 255х255

In [8]:
import cv2
import numpy as np

In [9]:
size = 255
horizontal_gradient1 = np.zeros([size, size])

2.2 Визначити розміри масиву

In [10]:
w = horizontal_gradient1.shape[1]
h = horizontal_gradient1.shape[0]

2.3 Поелементно змінити яскравості кожного пікселя

In [13]:
for i in range(size):
    for j in range(size):
        horizontal_gradient1[j][i] = i

2.4 Записати зображення засабами OpenCV

In [14]:
cv2.imwrite('ex.jpg', horizontal_gradient1)

True

2.5 Аналогічно створити горизонтальний градієнт в інший бік

In [28]:
size = 255
horizontal_gradient2 = np.zeros([size, size])

w = horizontal_gradient2.shape[1]
h = horizontal_gradient2.shape[0]
for i in range(size):
    for j in range(size):
        horizontal_gradient2[size-1-j][size-1-i] = i
        
cv2.imwrite('ex1.jpg', horizontal_gradient2)

True

### Вертикальний градієнт

2.6 Створити нульовий масив розміром 255х255

In [29]:
vertical_gradient1 = np.zeros([size, size])

2.7 Визначити розміри масиву

In [30]:
w = vertical_gradient1.shape[1]
h = vertical_gradient1.shape[0]